baseURL = "https://r-intro-course.netlify.app/"
title = "Intro R"
author = "Gabriela Mathieu"
copyright = ""
languageCode = "en"
DefaultContentLanguage = "en"
hasCJKLanguage=true
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
disqusShortname = ""
googleAnalytics = ""
theme = ""

[markup.goldmark.renderer]
unsafe= true

[params]
description = """
Presentaciones del curso Introducción a la programación en R
"""
favicon = "img/favicon-32x32.png"
math = true # for introducing $KaTEX$
env = "production" # for Google Analytics and DISQUS.
useChineseFonts = true
bannerFont = "fonts/exampleFont"

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "Slides"
    weight = 1
    identifier = "slides"
    url = "/slides/"
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"  
    weight = 2

  [[menu.main]]
    name = "About"
    weight = 3
    identifier = "about"
    url = "/about/"


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
[social]
twitter="http://twitter.com/calcita3"
gitlab="http://gitlab.com/calcita"
github="http://github.com/calcita"
mail="mailto:gmathieu@gmx.com"

# any icon in layouts/partials/svg can be used by the name without the "-line.svg"
